In [1]:
%matplotlib notebook


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [86]:
# A CSV file containing all scraped data from https://www.3ders.org/pricecompare/3dprinters/
complete_data = '3d_printers.csv'

df = pd.read_csv(complete_data)
df.head()

,Shop,Country,Manufacturer,Model,Assembled,Build envelope(W x D x H mm),Image,Technology,Price(US$),Lead time
0,Makex,China,MakeX,Migo Basic with Laser Engraver option,Yes,100x120x120,NaN,FFF,$ 149.00,-
1,Makex,China,MakeX,Migo with Laser Engraver option,Yes,100x120x120,NaN,FFF,$ 249.00,-
2,New Matter,USA,New Matter,MOD-t 3D printe,Yes,150x100x125,NaN,FFF,$ 249.00,-
3,Cobblebot,USA,Cobblebot,Cobblebot 3D Printer,Yes,381x381x381,NaN,FFF,$ 299.00,-
4,Makex,China,MakeX,Migo L with Laser Engraver option,Yes,150x150x150,NaN,FFF,$ 319.00,-

In [3]:
# Show all printers that uses "FDM" technology which is used for medicin
df[df['Technology'].str.contains("FDM", na=False)]

,Shop,Country,Manufacturer,Model,Assembled,Build envelope(W x D x H mm),Image,Technology,Price(US$),Lead time
187,WASP,Italy,WASP,DeltaWASP 20 40 (option: clay kit),Yes,200 mm x 400 mm h,NaN,FDM/LDM,"$ 3,500.00",4 weeks
198,WASP,Italy,WASP,DeltaWASP 20 40 Turbo2 (standard version and w...,Yes,200 mm x 400 mm h,NaN,FDM/LDM,"$ 4,000.00",4 weeks
235,WASP,Italy,WASP,DeltaWASP 40 70 PRO (option: clay kit),Yes,400mm x 670 mm h,NaN,FDM/LDM,"$ 10,000.00",5 weeks
237,WASP,Italy,WASP,DeltaWASP 40 70 Industrial (standard version a...,Yes,400mm x 700 mm h,NaN,FDM,"$ 12,500.00",5 weeks
239,Stratasys,USA,Stratasys,uPrint SE,Yes,203x152x152,NaN,FDM,"$ 15,900.00",-
241,Stratasys,USA,Stratasys,uPrint SE Plus,Yes,203x203x152,NaN,FDM,"$ 18,769.00",-
242,WASP,Italy,WASP,"DeltaWASP 3MT Multitools (pellet extruder, Cla...",Yes,1000mm x 1000 mm h,NaN,FDM/LDM,"$ 24,000.00",5 weeks
244,WASP,Italy,WASP,DeltaWASP 3MT Industrial Multitools (Spitfire ...,Yes,900 mm x 1000 mm h,NaN,FDM,"$ 28,000.00",5 weeks

In [54]:
complete_data = 'countries.csv'

df_country = pd.read_csv(complete_data)
df_country.head()

  country   latitude  longitude                  name
0      AD  42.546245   1.601554               Andorra
1      AE  23.424076  53.847818  United Arab Emirates
2      AF  33.939110  67.709953           Afghanistan
3      AG  17.060816 -61.796428   Antigua and Barbuda
4      AI  18.220554 -63.068615              Anguilla

In [87]:

for i, country in df.iterrows():
    if country['Country'] == 'USA':
        df.at[i, 'Country'] = 'United States'
    elif country['Country'] == 'TaiWan':
        df.at[i, 'Country'] = 'Taiwan'
    elif country['Country'] == 'UK':
        df.at[i, 'Country'] = 'United Kingdom'
        
lat = []
long = []
for i, row in df_country.iterrows():
    for n, country in df.iterrows():
        if row['name'] == country['Country']:
            df.at[n, 'lat'] = row['latitude']
            df.at[n, 'long'] = row['longitude']

df.head()

,Shop,Country,Manufacturer,Model,Assembled,Build envelope(W x D x H mm),Image,Technology,Price(US$),Lead time,lat,long
0,Makex,China,MakeX,Migo Basic with Laser Engraver option,Yes,100x120x120,NaN,FFF,$ 149.00,-,35.86166,104.195397
1,Makex,China,MakeX,Migo with Laser Engraver option,Yes,100x120x120,NaN,FFF,$ 249.00,-,35.86166,104.195397
2,New Matter,United States,New Matter,MOD-t 3D printe,Yes,150x100x125,NaN,FFF,$ 249.00,-,37.09024,-95.712891
3,Cobblebot,United States,Cobblebot,Cobblebot 3D Printer,Yes,381x381x381,NaN,FFF,$ 299.00,-,37.09024,-95.712891
4,Makex,China,MakeX,Migo L with Laser Engraver option,Yes,150x150x150,NaN,FFF,$ 319.00,-,35.86166,104.195397